### ISSUE TITLE
icon.png path is not correct

### ISSUE THREAD

**Issue by rocky-hxh** [kabili207/zyrenth-overlay#1]
/resources/app/assets/icon.png

I checked the ebuild file and work directory, it should be:

app/resources/app/assets/icon.png

**Comment by kabili207** [comment]
Which ebuild are you referring to?

**Comment by rocky-hxh** [comment]
Sorry, I am late, it's postman.

**Comment by kabili207** [comment]
I believe I fixed this with c93eeee73a8bdbcd4262e31f7b23269aadfa719a. Can you verify if it build correctly for you?

**Comment by rocky-hxh** [comment]
HI, I think your fix works, thanks a lot.
