### ISSUE TITLE
x11-drivers/displaylink-driver-5.8 version bump

### ISSUE THREAD

**Issue by pacho2** [kabili207/zyrenth-overlay#4]
It was released some time ago

But the way, it would be interesting to use "elog" instead of "einfo" for these messages (or use readme.gentoo-r1.eclass) to ensure people won't miss the information if they are not looking into the emerge output
 * The DisplayLinkManager Init is now called dlm
 * 
 * You should be able to use xrandr as follows:
 * xrandr --setprovideroutputsource 1 0
 * Repeat for more screens, like:
 * xrandr --setprovideroutputsource 2 0
 * Then, you can use xrandr or GUI tools like arandr to configure the screens, e.g.
 * xrandr --output DVI-1-0 --auto

Thanks

**Comment by kabili207** [comment]
Resolved with 21e04ad
